@baseUrl = http://localhost:5000
@baggageID=
@userID=
@tripID=
@token=

### Create Baggage Data
POST {{baseUrl}}/baggages
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "trousers"
}

### Get all baggages
GET {{baseUrl}}/baggages
Authorization: Bearer {{token}}

### Get a specific baggage
GET {{baseUrl}}/baggages/{{baggageID}}
Authorization: Bearer {{token}}

### update a specific baggage
PATCH {{baseUrl}}/baggages/{{baggageID}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "T Shirt",
    "completed": true
}

### Delete a specific baggage
DELETE  {{baseUrl}}/baggages/{{baggageID}}
Authorization: Bearer {{token}}

### create a user
POST {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Test User",
    "email": "user@test.com",
    "password": "abcdefgh"
}

### Get all users
GET {{baseUrl}}/users
Authorization: Bearer {{token}}

### Get specific user
GET {{baseUrl}}/users/{{userID}}
Authorization: Bearer {{token}}

### update a user
PATCH {{baseUrl}}/users/{{userID}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "email": "user@test2.com"
}

### Delete specific user
DELETE {{baseUrl}}/users/{{userID}}
Authorization: Bearer {{token}}

### register a user
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "name": "Test User",
    "email": "user@test.com",
    "password": "abcdefgh"
}

### login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "user@test.com",
    "password": "abcdefgh"
}

### create a new trip
POST {{baseUrl}}/trips
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Trip to the moon",
  "startDate": "2025-12-15",
  "endDate": "2025-12-16",
  "budget": {
    "total": 1000
  },
  "destinations": ["Moon", "Mars", "Jupiter"]
}

### Get all trips
GET {{baseUrl}}/trips
Authorization: Bearer {{token}}

### Get a trip by id
GET {{baseUrl}}/trips/{{tripID}}
Authorization: Bearer {{token}}

### Update trip
PATCH {{baseUrl}}/trips/{{tripID}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "expenses": [
    {
        "name": "taxi",
        "amount": 600,
    }
  ],
}

### Delete a trip
DELETE {{baseUrl}}/trips/{{tripID}}
Authorization: Bearer {{token}}

### send trip invitation
POST {{baseUrl}}/trips/{{tripID}}/invite
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "collaboratorEmails": [
        "shashankj677@gmail.com"
    ]
}