@baseUrl = http://localhost:3000
@baggageId=
@userId=6a228da0016058169b4fc4d1
@tripId=6a228ea2016058169b4fc4d2
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTIyOGRhMDAxNjA1ODE2OWI0ZmM0ZDEiLCJpYXQiOjE3ODA2NDk1NjYsImV4cCI6MTc4MDczNTk2Nn0.30oPdjXwfByHc4G7liulaaxvWIyG2uvyBeP1s1go0PA
@invitationToken=

### Create Baggage Data
POST {{baseUrl}}/baggages
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "trousers"
}

### Get all baggages
GET {{baseUrl}}/baggages
Authorization: Bearer {{token}}

### Get a specific baggage
GET {{baseUrl}}/baggages/{{baggageId}}
Authorization: Bearer {{token}}

### update a specific baggage
PATCH {{baseUrl}}/baggages/{{baggageId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "T Shirt",
    "completed": true
}

### Delete a specific baggage
DELETE  {{baseUrl}}/baggages/{{baggageId}}
Authorization: Bearer {{token}}

### create a user
POST {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Test User",
    "email": "user@test.com",
    "password": "abcdefgh"
}

### Get all users
GET {{baseUrl}}/users
Authorization: Bearer {{token}}

### Get specific user
GET {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{token}}

### update a user
PATCH {{baseUrl}}/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "email": "user@test2.com"
}

### Delete specific user
DELETE {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{token}}

### register a user
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "name": "Test User",
    "email": "user@test.com",
    "password": "abcdefgh"
}

### login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "user@test.com",
    "password": "abcdefgh"
}

### create a new trip
POST {{baseUrl}}/trips
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Trip to the moon",
  "startDate": "2025-12-15",
  "endDate": "2025-12-16",
  "budget": {
    "total": 1000
  },
  "destinations": ["Moon", "Mars", "Jupiter"]
}

### Get all trips
GET {{baseUrl}}/trips
Authorization: Bearer {{token}}

### Get a trip by id
GET {{baseUrl}}/trips/{{tripId}}
Authorization: Bearer {{token}}

### Update trip
PATCH {{baseUrl}}/trips/{{tripId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "expenses": [
    {
        "name": "taxi",
        "amount": 600,
    }
  ],
}

### Delete a trip
DELETE {{baseUrl}}/trips/{{tripId}}
Authorization: Bearer {{token}}

### send trip invitation
POST {{baseUrl}}/trips/{{tripId}}/invite
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "collaboratorEmails": [
        "shashankj677@gmail.com"
    ]
}

### Accept invite
GET {{baseUrl}}/trips/{{tripId}}/invite/accept?token={{invitationToken}}
Authorization: Bearer {{token}}
