@baseUrl = http://localhost:5000
@baggageId=6a0ecc700dc20417b0910d28

@userID=6a1407978ace9271b2a02e92
### Create Baggage Data
POST {{baseUrl}}/baggages
Content-Type: application/json

{
    "name": "Radhe Radhe"
}

### Get all baggages
GET {{baseUrl}}/baggages

### Get a specific baggage
GET {{baseUrl}}/baggages/{{baggageId}}

### update a specific baggage
PATCH {{baseUrl}}/baggages/{{baggageId}}
Content-Type: application/json

{
    "name": "T Shirt",
    "completed": true
}

### Delete a specific baggage
DELETE  {{baseUrl}}/baggages/{{baggageId}}

### create a user
POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "Test User",
    "email": "user@test.com",
    "password": "abcdefgh"
}

### Get all Users
GET {{baseUrl}}/users

### Get specific user
GET {{baseUrl}}/users/{{userID}}

### update a user
PATCH {{baseUrl}}/users/{{userID}}
Content-Type: application/json

{
    "email": "user@test2.com"
}

### Delete specific user
DELETE {{baseUrl}}/users/{{userID}}

### register a user
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "name": "Test User",
    "email": "user@test.com",
    "password": "abcdefgh"
}

### login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "user@test.com",
    "password": "abcdefgh"
}
